name: flutter_websocket_riverpod
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  auto_route: ^7.4.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  kartal: ^3.0.0
  lottie: ^2.4.0
  permission_handler: ^10.3.0
  pinput: ^2.2.31
  settings_ui: ^2.0.2
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^21.2.10
  web_socket_channel: ^2.4.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/fonts/
  #   - assets/images/
  #   - assets/jsons/
  #   - assets/lang/
  #   - assets/lotties/
  #   - assets/ss/
  #   - assets/svg/
  # Add Custom Fonts
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Black.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
